name: Build and deploy Flutter app to Azure Web App - INFS803-Movie-Web-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web

      - name: Zip artifact for deployment
        run: zip -r release.zip build/web

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: flutter-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: flutter-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D168574A47F8499A810DDA20DD0A11A7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B7967F8E6DEF46318FC944DD43A042BC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E97E30DC5A9E409AA5616A007E02536E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'INFS803-Movie-Web-App'
          slot-name: 'Production'
          package: build/web
