name: Web Release

on:
  push:
    branches:  [ "master", "main" ]

  pull_request:
    branches: [ "master", "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Web Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4.1.4
        
      - name: setup java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.6'

      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build web --release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
