name: Web Release

on:
  push:
    branches:  [ "master" ]

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Web Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4.1.4
        
      - name: setup java
        uses: actions/setup-java@v4.2.1
        with: 
          distribution: 'adopt'

      - name: build gradle
        run: ./gradlew build

      - name: upload a build artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: movie.apk
          path: app/build/outputs/apk/app-debug.apk
        
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "3.19.6"
  #         channel: 'stable'
  #         cache: true
      
  #     - name: Get dependencies
  #       run: flutter pub get

  #     - name: Start Web Release Build
  #       run: flutter build web --release
     
  #     - name: Upload Web Build Files
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: web-release
  #         path: ./build/web

  # deploy:
  #   name: Deploy Web Build
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Download Web Release
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: web-release

  #   - name: Deploy to gh-pages
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       publish_dir: ./
